### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by dwedaz** [megahertz/guzzle-tor#1]
can't pull your repo...

composer.phar require megahertz/guzzle-tor

[InvalidArgumentException]
  Could not find package megahertz/guzzle-tor at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by megahertz** [comment]
Thank you for feedback. Unfortunately, I can fix it only after 10 days. A temporary solution is to set minimum-stability to "dev"

**Comment by megahertz** [comment]
Fixed 89789667ae06260cd058679e6f6b0281cc1efd3a
